# Generated by Django 2.2.5 on 2019-11-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ersevent',
            name='name',
            field=models.TextField(),
        ),
    ]
