# Generated by Django 2.2.5 on 2019-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERS', '0003_auto_20191103_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ersevent',
            name='event_name',
            field=models.TextField(blank=True),
        ),
    ]
